### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by bbearce** [noraj1337/mkdocs-windmill-dark#3]
Hi,

I made a mkdocs documentation site and when I use this theme, the search function stops working. A copy of my mkdocs.yml is shown below:

```yaml
site_name: Ben's Code Journal
nav:
    - Home: index.md
    - Python: 
        - Installs: python/Installs.md
        - Useful: 
            - map(): python/useful/Map.md
            - input(): python/useful/Input.md
            - Sets: python/useful/Sets.md
            - P.B. Reference: python/useful/Pass By Reference.md
            - args, kwargs: python/useful/Args and Kwargs.md
            - zip(): python/useful/Zip.md
            - sorted(): python/useful/Sorted.md
        - Base Modules: 
            - Collection:
                - Counter: python/base_modules/collections/Counter.md
                - default_dict(): python/base_modules/collections/Default Dict.md
        - Advanced: 
            - Decorators: python/advanced/Decorators.md
            - Classes: python/advanced/Classes.md
            - Generators: python/advanced/Generators.md
        - Strings: python/strings/Strings.md
    - SQL:
        - Postgres: sql/postgres/Postgres.md
        - SQL server: sql/sql_server/Sql Server.md
        - sqlite: sql/sqlite/Sqlite.md
    - Javascript: javascript/Javascript.md
    - Bash: bash/tar_files.md
    - MKDocs: Quick Notes.md
extra_css:
    - css/extra.css
theme:
    name: windmill-dark
    highlightjs: true
    hljs_style: obsidian
```

The navigation is awesome and works perfectly. I was hoping the search would too. Any ideas why this might be happening?

Ex shot of no search results:
![image](https://user-images.githubusercontent.com/7649007/64365924-22ce9300-cfe3-11e9-8e8f-c34562f6c013.png)

Ex shot of the same thing but after hitting enter:
![image](https://user-images.githubusercontent.com/7649007/64366010-4eea1400-cfe3-11e9-9f7e-590e6d419592.png)
